apiVersion: v1
kind: Namespace
metadata:
  name: k4wd
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: k4wd
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k4wd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: k4wd
spec:
  selector:
    app: nginx
  ports:
    - name: http-alt
      port: 8080
      targetPort: 80
