on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
    - name: Test k4wd (unit tests)
      run: go test -v ./...
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Build k4wd
        run: go build ./cmd/k4wd
      - name: Start k3d
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: k4wd
      - name: Apply testing manifests
        run: |
          sleep 10
          kubectl config use-context k3d-k4wd
          kubectl apply -k test/integration
          kubectl -n k4wd wait --for=condition=Ready pods --all
          sleep 10
      - name: Test k4wd (including integration tests)
        run: K4WD_INTEGRATION_TESTS=true go test -v ./...
